version: '3.3'
services:
   db:
     container_name: DB_WCAROLINA 
     image: mariadb
     ports: 
       - "3306:3306"
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: WCAROLINA
       MYSQL_DATABASE: WCAROLINA
       MYSQL_USER: WCAROLINA
       MYSQL_PASSWORD: WCAROLINA

   wordpress:
     container_name: WP_WCAROLINA 
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - .:/var/www/html/wp-content/
     ports:
       - "9000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: WCAROLINA
       WORDPRESS_DB_PASSWORD: WCAROLINA
       WORDPRESS_DB_NAME: WCAROLINA
       WORDPRESS_DEBUG: "true"
volumes:
    db_data: {}